spring:
  application:
    name: employee-service

  config:
    import: "optional:configserver:http://localhost:8888"
#    import: "optional:configserver:http://192.168.99.100:8888"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.99.100:5442/guava_pay_employee_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: public